# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/ for available options

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: demo-go
  
  golint:
    min-confidence: 0.8
  
  govet:
    enable-all: true
    settings:
      shadow:
        strict: true
  
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - demo-go
          - github.com/gorilla/mux
          - github.com/go-redis/redis/v8
          - github.com/google/uuid
          - go.uber.org/zap
          - go.uber.org/zap/zapcore
          - go.mongodb.org/mongo-driver
          - github.com/golang-jwt/jwt/v4
          - github.com/golang-jwt/jwt/v5
          - golang.org/x/crypto
  
  lll:
    line-length: 120
  
  maligned:
    suggest-new: true
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: false
    require-explanation: true
    require-specific: true

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  
  disable:
    - gochecknoglobals
    - godox

issues:
  exclude-dirs:
    - vendor
    - internal/graphql/generated.go
  exclude-files:
    - ".*_gen.go$"
    - ".*\\.pb\\.go$"
  uniq-by-line: true
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - lll
    
    # Exclude known linter issues
    - path: internal/handler/
      text: "weak cryptographic primitive"
      linters:
        - gosec
    
    # Exclude shadow checking in type switches
    - text: "shadow: declaration of \"err\" shadows declaration at"
      linters:
        - govet
    
    # Exclude empty branch warnings for proper error handling
    - text: "SA9003: empty branch"
      linters:
        - staticcheck
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
