# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/ for available options

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - internal/graphql/generated.go
  skip-files:
    - ".*_gen.go$"
    - ".*\\.pb\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: demo-go
  
  golint:
    min-confidence: 0.8
  
  govet:
    check-shadowing: true
    enable-all: true
  
  lll:
    line-length: 120
  
  maligned:
    suggest-new: true
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: false
    require-explanation: true
    require-specific: true

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  
  disable:
    - gochecknoglobals
    - godox

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    
    # Exclude known linter issues
    - path: internal/handler/
      text: "weak cryptographic primitive"
      linters:
        - gosec
    
    # Exclude shadow checking in type switches
    - text: "shadow: declaration of \"err\" shadows declaration at"
      linters:
        - govet
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
