name: CI/CD Pipeline - Build and Deploy to Render

# This CI/CD pipeline uses project scripts for consistency between local development and CI/CD
# All build, test, lint, and security operations use the same scripts that developers use locally
# Scripts are located in the ./scripts/ directory and can be executed via Makefile targets

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read
  packages: write

env:
  GO_VERSION: '1.21'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Test and lint the Go code using project scripts
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Make scripts executable
      run: chmod +x scripts/*.sh

    - name: Setup project dependencies via script
      run: scripts/project.sh setup

    - name: Format code via script
      run: scripts/project.sh format

    - name: Lint code via script
      run: scripts/project.sh lint

    - name: Run tests via script
      env:
        REDIS_ADDRESS: localhost:6379
        MONGODB_URI: mongodb://admin:password@localhost:27017
        JWT_SECRET: test-secret-key
        CACHE_TYPE: redis
        REPOSITORY_TYPE: mongodb
      run: scripts/project.sh test coverage

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html

  # Security scanning using project scripts
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Make scripts executable
      run: chmod +x scripts/*.sh

    - name: Setup project dependencies via script
      run: scripts/project.sh setup

    - name: Run security scan via script
      run: scripts/project.sh security
      continue-on-error: true  # Don't fail the build on security warnings

    - name: Upload Gosec scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('gosec-results.sarif') != ''
      with:
        sarif_file: 'gosec-results.sarif'

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('trivy-results.sarif') != ''
      with:
        sarif_file: 'trivy-results.sarif'

  # Build Docker image with project scripts
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.event_name == 'push'
    
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tag: ${{ steps.meta.outputs.tags }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Make scripts executable
      run: chmod +x scripts/*.sh

    - name: Setup project dependencies via script
      run: scripts/project.sh setup

    - name: Build project via script
      run: scripts/project.sh build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          GO_VERSION=${{ env.GO_VERSION }}
          BUILD_TIME=${{ github.event.head_commit.timestamp }}
          GIT_COMMIT=${{ github.sha }}
          GIT_BRANCH=${{ github.ref_name }}

    - name: Generate SBOM
      uses: anchore/sbom-action@v0.17.2
      with:
        image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}
        format: spdx-json
        output-file: sbom.spdx.json
      continue-on-error: true  # Don't fail the build if SBOM generation fails

    - name: Alternative SBOM generation using Syft directly
      if: failure()  # Only run if the previous step failed
      run: |
        # Install syft directly
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        # Generate SBOM for the source code
        syft . -o spdx-json=sbom.spdx.json
      continue-on-error: true

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      if: always() && hashFiles('sbom.spdx.json') != ''
      with:
        name: sbom
        path: sbom.spdx.json

  # Deploy to Render (staging)
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    environment: staging
    
    steps:
    - name: Deploy to Render Staging
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_STAGING_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true

    - name: Run health check
      run: |
        sleep 30  # Wait for deployment to settle
        curl -f ${{ secrets.STAGING_HEALTH_URL }}/health || exit 1

    - name: Run smoke tests
      run: |
        echo "Running smoke tests against staging environment..."
        curl -f ${{ secrets.STAGING_HEALTH_URL }}/health
        # Add more smoke tests here

  # Deploy to Render (production)
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build  # Only depend on build, not staging
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    
    steps:
    - name: Deploy to Render Production
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_PRODUCTION_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true

    - name: Run health check
      run: |
        sleep 30  # Wait for deployment to settle
        curl -f ${{ secrets.PRODUCTION_HEALTH_URL }}/health || exit 1

    - name: Run production smoke tests
      run: |
        echo "Running smoke tests against production environment..."
        curl -f ${{ secrets.PRODUCTION_HEALTH_URL }}/health
        # Add more comprehensive smoke tests here

    - name: Notify deployment success
      uses: 8398a7/action-slack@v3
      if: success()
      with:
        status: success
        channel: '#deployments'
        text: '🚀 Production deployment successful! Image: ${{ needs.build.outputs.image-tag }}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

    - name: Notify deployment failure
      uses: 8398a7/action-slack@v3
      if: failure()
      with:
        status: failure
        channel: '#deployments'
        text: '❌ Production deployment failed! Please check the logs.'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  # Performance testing
  performance-test:
    name: Performance Test
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run load tests with k6
      uses: grafana/k6-action@v0.2.0
      with:
        filename: tests/load-test.js
      env:
        K6_OUT: json=results.json
        BASE_URL: ${{ secrets.STAGING_HEALTH_URL }}

    - name: Upload performance test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-test-results
        path: results.json

  # Cleanup old images
  cleanup:
    name: Cleanup Old Images
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Delete old container images
      uses: actions/delete-package-versions@v4
      with:
        package-name: ${{ github.event.repository.name }}
        package-type: 'container'
        min-versions-to-keep: 5
        delete-only-untagged-versions: true
